//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisteme_te_shprendara_databaza.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SherbimetSoap")]
    public interface SherbimetSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Regjistrohu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Regjistrohu(string emri, string mbiemri, string gjinia, string datelindja, string passwordi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Regjistrohu", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegjistrohuAsync(string emri, string mbiemri, string gjinia, string datelindja, string passwordi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kyqu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Kyqu(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kyqu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> KyquAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rezultatet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Rezultatet(string lojtari_1, string lojtar_2, float rezul_1, float rezul_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rezultatet", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RezultatetAsync(string lojtari_1, string lojtar_2, float rezul_1, float rezul_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kush_ka_luajtur", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Kush_ka_luajtur(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kush_ka_luajtur", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Kush_ka_luajturAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_rezultati", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool update_rezultati(string lojtari_1, float rezul_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_rezultati", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> update_rezultatiAsync(string lojtari_1, float rezul_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selekto_Rezultatet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet selekto_Rezultatet(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selekto_Rezultatet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> selekto_RezultatetAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SherbimetSoapChannel : Sisteme_te_shprendara_databaza.ServiceReference1.SherbimetSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SherbimetSoapClient : System.ServiceModel.ClientBase<Sisteme_te_shprendara_databaza.ServiceReference1.SherbimetSoap>, Sisteme_te_shprendara_databaza.ServiceReference1.SherbimetSoap {
        
        public SherbimetSoapClient() {
        }
        
        public SherbimetSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SherbimetSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SherbimetSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SherbimetSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Regjistrohu(string emri, string mbiemri, string gjinia, string datelindja, string passwordi) {
            return base.Channel.Regjistrohu(emri, mbiemri, gjinia, datelindja, passwordi);
        }
        
        public System.Threading.Tasks.Task<bool> RegjistrohuAsync(string emri, string mbiemri, string gjinia, string datelindja, string passwordi) {
            return base.Channel.RegjistrohuAsync(emri, mbiemri, gjinia, datelindja, passwordi);
        }
        
        public System.Data.DataSet Kyqu(string username, string password) {
            return base.Channel.Kyqu(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> KyquAsync(string username, string password) {
            return base.Channel.KyquAsync(username, password);
        }
        
        public bool Rezultatet(string lojtari_1, string lojtar_2, float rezul_1, float rezul_2) {
            return base.Channel.Rezultatet(lojtari_1, lojtar_2, rezul_1, rezul_2);
        }
        
        public System.Threading.Tasks.Task<bool> RezultatetAsync(string lojtari_1, string lojtar_2, float rezul_1, float rezul_2) {
            return base.Channel.RezultatetAsync(lojtari_1, lojtar_2, rezul_1, rezul_2);
        }
        
        public System.Data.DataSet Kush_ka_luajtur(string username) {
            return base.Channel.Kush_ka_luajtur(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Kush_ka_luajturAsync(string username) {
            return base.Channel.Kush_ka_luajturAsync(username);
        }
        
        public bool update_rezultati(string lojtari_1, float rezul_2) {
            return base.Channel.update_rezultati(lojtari_1, rezul_2);
        }
        
        public System.Threading.Tasks.Task<bool> update_rezultatiAsync(string lojtari_1, float rezul_2) {
            return base.Channel.update_rezultatiAsync(lojtari_1, rezul_2);
        }
        
        public System.Data.DataSet selekto_Rezultatet(string username) {
            return base.Channel.selekto_Rezultatet(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> selekto_RezultatetAsync(string username) {
            return base.Channel.selekto_RezultatetAsync(username);
        }
    }
}
